### ISSUE TITLE
gretel adds spurious SNPs ???

### ISSUE THREAD

**Issue by Sebdu132** [SamStudio8/gretel#22]
Hi Sam,

first of all, thanks for developping such an algorithm, finding haplotypes of specific genes in metagenomes is exactly what I need now ! I was desperate with all the for-human-designed haplotype callers.

But before using it in routine, I tested it on a small part of my data to see its efficiency, and I got some surprising results. Instead of the three expected haplotypes, gretel gave me five, two of them being related of correct ones but with spurious SNPs.
These SNP doesn't exist in the reads, I've visually checked it (in ARTEMIS), nor in the VCF file. Interestingly, these errors occur only at positions with already a SNP (i.e. it creates 2 variants instead of one, most of the time).

I give you all the data for you to have a look:  
- the reference sequence cat_3.fasta, the aligned bam file, the vcf file created by FreeBayes (with haplotypes disabled), the log file of the gretel execution, and the output out.fasta to which I added the reference sequence for comparison in my GUI sequence aligner.

[cat_3.GRETELanalysis.tar.gz](https://github.com/SamStudio8/gretel/files/1928480/cat_3.GRETELanalysis.tar.gz)

Look at positions 330, (411, 417, 432, 438, 448, 453, 457, 459, 507,508,522,538,546 all in the same haplotype), 555, and 603.
Of particular interest is the SNP at position 448: 2 reads have a T instead of A, and gretel returns a G variant instead.

Tell me if it is a bug of if my data have a problem.

I also noticed that the 5 last positions (> 603 in the vcf file) are not included in the haplotypes despite being well supported and positioned on reads having detected variants. 

 I really hope you can help me with this, because I am a huge fan of your tool (if it works...).

Sebastien.

**Comment by SamStudio8** [comment]
Hi Sebastien!
Sorry to hear you are having some trouble, I'll investigate. Can I ask what generated the BAM that you've attached as I'm unable to index it with samtools...?

```
samtools index FK.oncat3.bam                                                                                                                                                                
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated.
```

My MD5 for the file is:
```
9a8958f104c14e5cd5b10a7f8ead3de9  FK.oncat3.bam
```

**Comment by Sebdu132** [comment]
Hi Samuel,
sorry I forgot to give you the BAM index file. For me indexing worked perfectly with bamtools index. Here is the file:

[FK.oncat3.bam.bai.zip](https://github.com/SamStudio8/gretel/files/1931119/FK.oncat3.bam.bai.zip)

I created the SAM with bowtie2 --local --score-min L,10,0.8 (relaxed mapping but not as much as you can do, I am searching only close variants), and the BAM with the command samtools view -bS -h $SAM | bamtools sort > $TMPBAM

but I also added a readgroup with the command:
bamaddrg -b $TMPBAM -s $id > $BAM

maybe that's the problem why you can't add an index with samtools. I am using samtools 1.8 with htslib 1.8, and bamtools 2.4.0

**Comment by SamStudio8** [comment]
Hi Sebastien,
Sadly with your BAI, I'm still having trouble with your BAM!
When I try and run Gretel on my machine, I get this error:
```
Traceback (most recent call last):
  File "/usr/bin/gretel", line 11, in <module>
    load_entry_point('gretel==0.0.81', 'console_scripts', 'gretel')()
  File "build/bdist.linux-x86_64/egg/gretel/cmd.py", line 30, in main
    commands that have no complete_ method.
  File "build/bdist.linux-x86_64/egg/gretel/util.py", line 30, in get_ref_len_from_bam
  File "pysam/libcalignmentfile.pyx", line 729, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 930, in pysam.libcalignmentfile.AlignmentFile._open
  File "pysam/libchtslib.pyx", line 364, in pysam.libchtslib.HTSFile.check_truncation
IOError: no BGZF EOF marker; file may be truncated
```
Did you try and subset the reads for this specific contig from your main BAM? If so, maybe it's led to a malformed file, [I have some pitfalls and tips on subsetting reads](https://samnicholls.net/2016/01/10/not-bam-subset/#correct). Either that, would you be willing to send me the whole BAM?

At the very least, I think I've confirmed this as a bug, as given your log (thanks for the comprehensive report) and taking focus at position 448, I see that Gretel actually believes there are indeed alternative "spurious" SNPs that are not supported by the reads.

```
i	pos	gap	A	C	G	T	N	-	_	tot
[...]
52	448	7	23	3	7	2	0	0	0	35
[...]
```

Can you double check that I've got the right BAM? Or if you subset it yourself, can you try and do it with GATK as per my link above? Or would you mind sending me the whole original BAM?

**Comment by Sebdu132** [comment]
Ok, I don't know what happened with this file, I didn't subset it or anything other that I told you. But it seems corrupted on my computer too.
So here is the freshly computed SAM, BAM and BAI files, directly output from bowtie2:
[Gretel_cat3.zip](https://github.com/SamStudio8/gretel/files/1931975/Gretel_cat3.zip)
 
I hope you will be able to open this one and fix the bug, because I've tested on another gene, and I had the same spurious SNPs... critical.

Keep me in touch.

**Comment by SamStudio8** [comment]
Hi Sebastien,
Thanks for your BAM, I can replicate the problem and have done some extensive testing!

I have good and bad news. The good news is, I've tracked the issue down to overlapping mate pairs, but the bad news is, this appears to be behaviour arising out of `pysam`, not `Gretel`, so a fix requires me to do some research and some more testing.

From what I can work out, when you have an overlapping mate pair, the secondary read seems to have its SNPs suppressed from the `pysam` pileup on those overlapping sites. This is causing our "SNP string" for the secondary read to be some `n` overlapping SNP sites too short, **but** the offset is still correct, which essentially means we are adding information to `Hansel` with an incorrect offset of `n`, which is way you are seeing these spurious SNPs.

I'll keep you posted on my findings. Thanks again for taking the time to report this and provide testing data.

**Comment by SamStudio8** [comment]
I've tracked down some undocumented `pysam` options for `pileup`, and I have fixed this bug.
A commit will follow to resolve shortly, and I've tried to clarify the docs situation with `pysam` (see See https://github.com/pysam-developers/pysam/issues/671).

Thanks again Sebastien.

**Comment by SamStudio8** [comment]
Sebastien, please update your installation to v0.0.90, and all should be well.

**Comment by Sebdu132** [comment]
Hi Sam,
Thanks a lot for the fix ! However I have another problem. I explain it in another post in order to separate the issues.

Sebastien.
